### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by cyris69** [KaiKikuchi/Dynmap-GriefPreventionPlus#4]
I have the most recent version of forge dynmap which workls perfectly.
This is the error, also off topic but does forge restricter auto add the mods it can find for GPP protection or does I have to manually add the mods?

[15:03:34] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins/Dynmap-GriefPreventionPlus-0.9.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: dynmap
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:223) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by KaneHart** [comment]
Same issue:
[21:42:25] [Server thread/ERROR]: Could not load 'plugins/Dynmap-GriefPreventionPlus-0.9.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: dynmap
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:223) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by spannerman79** [comment]
Read http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft properly.

Hint: Don't skim

**Comment by KaneHart** [comment]
See this one is just as bad as Vault being required for GPP and yet they show requirements and options but not vault then when people keep asking their like wtf GP requires it how don't you know this. . If you fork a mod or create a mod create some basic documentation like requirements. Just because you have tons of free time in life to masturbate does not mean we all do.

**Comment by spannerman79** [comment]
> See this one is just as bad as Vault being required for GPP and yet they show requirements and options but not vault then when people keep asking their like wtf GP requires it how don't you know this. . If you fork a mod or create a mod create some basic documentation like requirements. Just because you have tons of free time in life to masturbate does not mean we all do.

Your **own log** ( `org.bukkit.plugin.UnknownDependencyException: dynmap` ) states what the issue is - and yet you jump up and down like a little 2/3 year old throwing a tantrum when you are directed to the place **where your actual issue is located**.

**Comment by KaiKikuchi** [comment]
> Just because you have tons of free time in life [..] does not mean we all do.

I cannot allow such attitude towards people who are doing free work while you're probably making profit on it. Shame.

Whether I have free time to do my own private things is none of your business. I decide how to spend my free time, and it won't be by helping you.

@spannerman79 thanks for the constant help you provide to those who ask for help on my repos.
